//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPYDF.Model.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Houses
    {
        public int HouseID { get; set; }
        public string Name { get; set; }
        public int ResourceType { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public Nullable<int> IsJoint { get; set; }
        public Nullable<int> HouseType { get; set; }
        public Nullable<int> HouseFloor { get; set; }
        public string LinkPhone { get; set; }
        public Nullable<int> TotalFloor { get; set; }
    }
}
