//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPYDF.Model.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int UserType { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreatedById { get; set; }
        public int Status { get; set; }
        public string LoginAccount { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> ModTime { get; set; }
        public Nullable<int> ModById { get; set; }
        public string UserPhoto { get; set; }
    }
}
